export const NEW_RELEASE_LOADING = 'NEW_RELEASE_LOADING'
export const NEW_RELEASE_SUCCESS = 'NEW_RELEASE_SUCCESS'
export const NEW_RELEASE_ERROR = 'NEW_RELEASE_ERROR'

export const PLAYLISTS_LOADING = 'PLAYLISTS_LOADING'
export const PLAYLISTS_SUCCESS = 'PLAYLISTS_SUCCESS'
export const PLAYLISTS_ERROR = 'PLAYLISTS_ERROR'

export const CATEGORIES_LOADING = 'CATEGORIES_LOADING'
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS'
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR'
